language: shell
os: windows
before_install:
  - choco install python --version=3.8
  - python -m pip install --upgrade pip

env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt


scripts:
  - python -m test.test_program
  - pyinstaller --onefile app.py
  - python deploy.py