client_config_backend: settings
client_config:
  client_id: 629967102041-b020ke70bmrl8vaganvj3s2sfu63vdh4.apps.googleusercontent.com
  client_secret: d2muTTtCMGYBPIkhKhQ6bEa_

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True